const colors = ['Almond', 'AntiqueBrass', 'Apricot', 'Aquamarine', 'Asparagus', 'AtomicTangerine', 'BananaMania', 'Beaver', 'Bittersweet', 'Black', 'Blue', 'BlueBell', 'BlueGreen', 'BlueViolet', 'Bluetiful', 'Blush', 'BrickRed', 'Brown', 'BurntOrange', 'BurntSienna', 'CadetBlue', 'Canary', 'CaribbeanGreen', 'CarnationPink', 'Cerise', 'Cerulean', 'Chesnut', 'Copper', 'Cornflower', 'CottonCandy', 'Denim', 'DesertSand', 'Eggplant', 'ElectricLime', 'Fern', 'ForestGreen', 'Fuchisia', 'FuzzyWuzzyBrown', 'Gold', 'Goldenrod', 'GrannySmithApple', 'Gray', 'Green', 'GreenYellow', 'HotMagenta', 'InchWorm', 'Indigo', 'JazzberryJam', 'JungleGreen', 'LaserLemon', 'Lavender', 'MacaroniandCheese', 'Magenta', 'Mahogany', 'Manatee', 'MangoTango', 'Maroon', 'Mauvelous', 'Melon', 'MidnightBlue', 'MountainMeadow', 'NavyBlue', 'NeonCarrot', 'OliveGreen', 'Orange', 'Orichid', 'OuterSpace', 'OutrageousOrange', 'PacificBlue', 'Peach', 'Periwinkle', 'PiggyPink', 'PineGreen', 'PinkFlamingo', 'PinkSherbet', 'Plum', 'PurpleHeart', "PurpleMountains'Magesty", 'PurplePizza', 'RadicalRed', 'RawSienna', 'RazzleDazzleRose', 'Razzmatazz', 'Red', 'RedOrange', 'RedViolet', 'RobinEggBlue', 'RoyalPurple', 'Salmon', 'Scarlet', 'ScreaminGreen', 'SeaGreen', 'Sepia', 'Shadow', 'Shamrock', 'ShockingPink', 'Silver', 'SkyBlue', 'SpringGreen', 'Sunglow', 'SunsetOrange', 'Tan', 'TickleMePink', 'Timberwolf', 'TropicalRainForest', 'Tumbleweed', 'TurquoiseBlue', 'UnmellowYellow', 'Violet(Purple)', 'VioletRed', 'VividTangerine', 'VividViolet', 'White', 'WildBlueWonder', 'WildStrawberry', 'WildWatermelon', 'Wisteria', 'Yellow', 'YellowGreen', 'YellowOrange'];

const animals = ['Aardvark', 'Aardwolf', 'AbyssalSeaCucumber', 'Addax', 'Amblypygi', 'Amphibean', 'Anglerfish', 'Ant', 'Ape', 'Arachnid', 'Arthropod', 'Aye-Aye', 'Baboon', 'Badger', 'Barreleye', 'Bat', 'Bear', 'Bird', 'Black-FootedFerret', 'BoaConstrictor', 'Butterfly', 'Camel', 'Cat', 'Cassowary', 'Centipede', 'Chameleon', 'Chimpanzee', 'Cobra', 'Cockroach', 'Coelacanth', 'Coral', 'Crab', 'Crocodile', 'Crustacean', 'Cuttlefish', 'DeepSeaHatchetfish', 'Deer', 'Dog', 'Dolphin', 'Dormouse', 'Dragonfly', 'Eagle', 'Eel', 'Elephant', 'Elk', 'ElkBotfly', 'Falcon', 'Ferret', 'Fish', 'Fly', 'Fox', 'Frog', 'Gharial', 'Giraffe', 'GiraffeWeevil', 'GoblinShark', 'GranrojoJellyfish', 'Gull', 'Guineafowl', "Harris'Hawk", 'Hatchetfish', 'Hellbender', 'Hippopotamus', 'HoneyBadger', 'HoneyBee', 'Horse', 'Hummingbird', 'Hyena', 'Ibex', 'Ibis', 'Insect', 'Invertebrate', 'Jaguar', 'Jaguarundi', 'Jaybird', 'Jellyfish', 'Kangaroo', 'Koala', 'Kestrel', 'Lion', 'Lionfish', 'Lobster', 'Mammal', 'MantaRay', 'MarabouStork', 'Marsupial', 'MataMata', 'MatusubaKoi', 'Mink', 'Mollusk', 'Monkey', 'Monotreme', 'Mouse', 'Narwhal', 'NorthernBaldIbis', 'Octopus', 'Ostrich', 'Otter', 'Owl', 'Pangolin', 'Parrot', 'Peacock', 'Pelican', 'Penguin', 'Pig', 'Platypus', 'PrayingMantis', 'PromachoteuthisSulcus', 'Python', 'Quail', 'Quetzal', 'Rabbit', 'Raccoon', 'Rat', 'Reptile', 'Rhinoceros', 'SeaCucumber', 'Scorpion', 'Shark', 'Sheep', 'Shrimp', 'Skunk', 'Snake', 'Sparrow', 'Spider', 'Squid', 'Squirrel', 'StarNosedMole', 'TheridionGrallatora', 'Tiger', 'Turtle', 'Umbrellabird', 'VampireBat', 'Vertebrate', 'Wallaby', 'Wasp', 'Weasel', 'Whale', 'Wolf', 'Wolf-trapAnglerfish', 'Worm', 'Yak', 'Zebra', 'Zorilla'];

const randomName = () => {
  const randColor = colors[Math.floor(Math.random() * colors.length)];
  const randAnimal = animals[Math.floor(Math.random() * animals.length)];

  return (randColor.concat(randAnimal));
};

exports.randomName = randomName;
